config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'tasks#index'
  resources :tasks do
    collection do
      get :search
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  validate :varidate_name_not_including_comma

  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags

  scope :recent, -> { order(created_at: :desc)}
  scope :priority_sorted, -> { order(priority: :desc) }

  enum status:{未着手:0, 着手:1, 完了:2}
  enum priority:{高:0, 中:1, 低:2}
  scope :name_like, -> (name) { where('name LIKE ?', "%#{ name }%") if name.present? }
  scope :status, -> (status) { where(status: status) if status.present? }
  scope :tag_id, -> (tag_id) {
    joins(:task_tags).where(task_tags: {tag_id: tag_id}) if tag_id.present?
  }

  private

  def varidate_name_not_including_comma
    errors.add(:name, 'にコンマを含めることはできません') if name&.include?(',')
  end

  def self.lastest(number)
    order(created_at: :desc).limit(number)
  end

  scope :searchh, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name]).status(search_params[:status]).tag_id(search_params[:tag_id])
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only:[:edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.page(params[:page]).per(5).order('created_at DESC')
    if params[:sort_expired]
      @tasks = @tasks .page(params[:page]).per(5).order('deadline ASC')
    elsif params[:pri_sort]
      @tasks = @tasks .page(params[:page]).per(5).order('priority ASC')
    else
      @tasks
    end
  end

  def search
    @search_params = task_search_params

    @tasks = current_user.tasks.searchh(@search_params).page(params[:page]).per(5)
      render :index
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
    redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      if params[:task][:tag_ids].present?
        @task.task_tags.each do |task_tag|
          task_tag.destroy if task_tag.task_id == @task.id
        end
        params[:task][:tag_ids].each do |tag_id|
          TaskTag.create(task_id: @task.id, tag_id: tag_id)
        end
      else
        @task.task_tags.each do |task_tag|
          task_tag.destroy if task_tag.task_id == @task.id
        end
      end
    else
      @task_tag_ids = @task.tags_attached_to_task.pluck(:id)
      render "edit"
    end
    redirect_to task_path(@task.id), notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :deadline, :status, :priority, { tag_ids: [] })
    .merge(status: params[:task][:status].to_i).merge(priority: params[:task][:priority].to_i)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_search_params
    params.fetch(:search, {}).permit(:name, :status, :tag_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
- if task.errors.present?
    ul#error_explanation
        - task.errors.full_messages.each do |message|
            li = message

= form_with model: task, local: true do |f|
    .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', id: 'task_name'
    .form-group
        = f.label :description
        = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
    .form-group
        = f.label :deadline
        = f.datetime_select :deadline, discard_hour: :true, discard_minute: :true, class: 'form-control'
    .form-group
        = f.label :status
        = f.select :status, options_for_select(Task.statuses), {prompt: "選択してください"}, class: "status-select"
    .form-group
        = f.label :priority
        = f.select :priority, options_for_select(Task.priorities), {prompt: "選択してください"}, class: "priority-select"
    .form-group
        = f.label :tag
        = f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name)
          / - Tag.all.each do |tag|
          /   - if action_name == 'new' || action_name == 'create'
          /     = f.check_box :tag_ids, { multiple: true, checked: tag[:checked], disabled: tag[:disabled], include_hidden: false}, tag[:id], ""
          /     tag = tag.tag_name
          /   - elsif action_name == 'edit' || action_name == 'update'
          /     = f.check_box :tag_ids, { multiple: true, checked: @task.tag_ids.include?(tag.id), disabled: tag[:disabled], include_hidden: false}, tag[:id], ""
          /     tag = tag.tag_name
    = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
    = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧
= form_with(model: @task, scope: :search, url: search_tasks_path, method: :get, local: true) do |f|
  .from-group.row
  = f.label :name, "Name"
  = f.text_field :name, id: 'search_name'
  = f.label :status, "status"
  = f.select :status, Task.statuses, {include_blank: '選択してください', selected: ''},  { id: 'search_status'}
  = f.label :tag_id, "tag"
  = f.select :tag_id, Tag.pluck(:tag_name, :id), { include_blank: '選択してください', selected: ''},  { id: 'search_tag'}
  = submit_tag '検索', class: "button"
  .from-group.row
    = link_to '新規登録', new_task_path, class: 'btn btn-primary'
  .from-group.row
    = link_to '終了期限でソートする', tasks_path(sort_expired: "true"), class: 'btn btn-danger'
    = link_to '優先順位でソートする', tasks_path(pri_sort: "true"), class: 'btn btn-danger'
.md-3
table.table.table-hover
  thead.thesd-default
    tr
      th = Task.human_attribute_name(:user)
      th = Task.human_attribute_name(:name)
      th = Task.human_attribute_name(:created_at)
      th = Task.human_attribute_name(:deadline)
      th = Task.human_attribute_name(:status)
      th = Task.human_attribute_name(:priority)
      th = Task.human_attribute_name(:tag)
      th
  tbody
    - @tasks.each do |task|
      tr
        td = task.user.name
        td = link_to task.name, task
        td = task.created_at
        td = task.deadline
        td = task.status
        td = task.priority
        td = task.tags.map(&:tag_name).join(', ')
        td
          = link_to '詳細', task_path(task.id), class: 'btn btn-default mr-3'
          = link_to "編集", edit_task_path(task), class: 'btn btn-primary mr-3'
          = link_to "削除", task, method: :delete, remote: true, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'
  = paginate @tasks

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
    = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/search.slim
- unless @search_params.blank?
  - @task.each do |task|
    tr
      td= task.name
      td= task.status

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:description)
      td = simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
    tr
      th = Task.human_attribute_name(:deadline)
      td = @task.deadline
    tr
      th = Task.human_attribute_name(:status)
      td = @task.status
    tr
      th = Task.human_attribute_name(:priority)
      td = @task.priority
    tr
      th = Task.human_attribute_name(:created_at)
      td = @task.created_at
    tr
      th = Task.human_attribute_name(:updated_at)
      td = @task.updated_at
    tr
      th = Task.human_attribute_name(:tag)
      td = @task.tags.map(&:tag_name).join(', ')

          / - task.tags.each do |tag|
          /   tag.tag_name

= link_to "編集", edit_task_path, class: 'btn btn-primary mr-3'
= link_to "削除", @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'