config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'tasks#index'
  resources :tasks do
    collection do
      get :search
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks, dependent: :destroy

  before_destroy :must_not_destroy_last_one_admin
  before_update :must_not_update_last_one_admin

  private

  def must_not_destroy_last_one_admin
    if User.where(admin: true).count == 1 && self.admin == true
      throw(:abort)
    end
  end

  def must_not_update_last_one_admin
    if User.where(admin: true).count == 1 && self.admin == false && self.changes[:admin].nil? == false
      throw(:abort)
      end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index, :show, :new, :edit, :update, :destroy]

  def index
    @users = User.all
    @tasks = Task.all.includes(:user)
  end

  def show
  end

  def new
    @user = User.new
    if check_admin
    end
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in
      redirect_to admin_user_path(@user), notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      redirect_to admin_users_path, notice: "ユーザ「#{@user.name}」を更新できません。"
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_url, notice: "ユーザ「#{@user.name}」を削除しました。"
    else
      redirect_to admin_users_path, notice: "最後の管理者は削除できません。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    unless current_user&.admin?
      redirect_to root_path, notice: "管理者以外はアクセスできません"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # def index
  #   if check_admin
  #   @users = User.all
  #   @tasks = Task.all.includes(:user)
  #   else
  #     redirect_to tasks_path, notice: "管理者以外はアクセスできません。"
  #   end
  # end

  def show
    @tasks = Task.where(user_id: @user.id).page(params[:page])
    if check_admin || current_user?
      render :show
    else
      redirect_to tasks_path, notice: "自分以外のユーザマイページにはアクセスできません。"
    end
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    end
  end

  def edit
    if current_user?
    else
      redirect_to tasks_path, notice: "自分以外の編集はできません。"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path, notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "ユーザ「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/_form.html.slim
- if user.errors.present?
    ul#error_explanation
        - user.errors.full_messages.each do |message|
            li = message

= form_with model: [:admin, user], local: true do |f|
    .form-group
        = f.label :name, '名前'
        = f.text_field :name, class: 'form-control', id: 'name-id'
    .form-group
        = f.label :email, 'メールアドレス'
        = f.text_field :email, class: 'form-control', id: 'email-id'
    .form-group
        = f.label :password, 'パスワード'
        = f.password_field :password, class: 'form-control', id: 'password-id'
    .form-group
        = f.label :password_confirmation, 'パスワード（確認）'
        = f.password_field :password_confirmation, class: 'form-control', id: 'confirmation-id'
    = f.submit '登録する', class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザの編集
.nav.justify-content-end
= render partial: 'form', locals: { user: @user }

app/views/users/new.html.slim
h1 ユーザ登録
.nav.justify-content-end
= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1 ユーザの詳細

.nav.justify-content-end
table.table.table-hover
    tbody
        tr
            th = User.human_attribute_name(:id)
            td = @user.id
        tr
            th = User.human_attribute_name(:name)
            td = @user.name
        tr
            th = User.human_attribute_name(:email)
            td = @user.email
        tr
            th = User.human_attribute_name(:admin)
            td = @user.admin? ? 'あり' : 'なし'
        tr
            th = User.human_attribute_name(:created_at)
            td = @user.created_at
        tr
            th = User.human_attribute_name(:updated_at)
            td = @user.updated_at
table.table.table-hover
    thead.thesd-default
        tr
            th = Task.human_attribute_name(:user)
            th = Task.human_attribute_name(:name)
            th = Task.human_attribute_name(:created_at)
            th = Task.human_attribute_name(:deadline)
            th = Task.human_attribute_name(:status)
            th = Task.human_attribute_name(:priority)
            th
    tbody
        - @user.tasks.each do |task|
            tr
                td = task.user.name
                td = link_to task.name, task
                td = task.created_at
                td = task.deadline
                td = task.status
                td = task.priority
                td
= link_to '編集', edit_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'
= link_to "タスク一覧画面へ戻る", tasks_path